name: CI

on:
  push:
    branches:
      - main
      - Antoine/root-helper-proper
    paths-ignore:
      - '**/*.md'
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Procursus
        uses: beer-psi/procursus-action@v2
        with:
          packages: ldid
          cache: true
          cache-path: ~/__cache

      - name: Select Xcode version (15.0)
        run: |
          sudo xcode-select --switch /Applications/Xcode_15.0.app

      - name: Build App
        run: |
          make

      - name: Package IPA Files
        run: |
          mkdir -p build
          mkdir -p Payload
          cp -r Santander.app Payload/
          
          # Build Jailed IPA
          zip -vr build/SantanderJailed.ipa Payload/
          
          # Build TrollStore TIPA
          cp build/SantanderJailed.ipa build/SantanderTrollStore.tipa

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SantanderJailed
          path: build/SantanderJailed.ipa

      - name: Upload IPA for TrollStore
        uses: actions/upload-artifact@v4
        with:
          name: SantanderTrollStore
          path: build/SantanderTrollStore.tipa
